import test from 'node:test';
import assert from 'node:assert/strict';
import {BULL_ARENA} from '../bull.mjs';
import {Match} from '../simulation.mjs';
function round(n=3){const m=new Match();m.selectGame('bull');const p=Array.from({length:n},(_,i)=>m.join('참가자'+i));m.chooseBull(p[0].id);m.start();return {m,b:p[0],h:p[1],p};}
test('random/designated bull, minimum capacity and rematch preserve identity',()=>{
  const m=new Match();m.selectGame('bull');const a=m.join('A');assert.throws(()=>m.start(),/2명/);const b=m.join('B');m.start();assert.equal([...m.players.values()].filter(p=>p.role==='bull').length,1);m.lobby();m.chooseBull(b.id);m.start();assert.equal(b.role,'bull');assert.equal(a.role,'human');assert.throws(()=>m.chooseBull(a.id),/대기실/);m.lobby();assert.equal(a.flight,null);assert.equal(a.survival,0);
});
test('bull advances without input, accelerates and turns less at higher speed',()=>{const {m,b,h}=round();h.x=15;h.z=0;const z=b.z;m.tick(.1);assert(b.z>z);assert(b.speed>7);b.speed=7;m.input(b.id,{steer:1},100);m.tick(.1,100);const slow=b.yaw;b.yaw=0;b.speed=15;m.input(b.id,{steer:1},100);m.tick(.1,100);assert(b.yaw<slow);assert(b.speed>5);});
test('human movement, turning and stale input are bounded by the arena',()=>{const {m,h}=round();h.x=0;h.z=-20;h.yaw=Math.PI;m.input(h.id,{forward:1,steer:0},100);m.tick(.1,100);assert(h.z<-20);const z=h.z;m.tick(.1,1000);assert.equal(h.z,z);m.input(h.id,{steer:1},1000);const yaw=h.yaw;m.tick(.1,1000);assert(h.yaw-yaw>.3);h.x=50;m.tick(.1,1000);assert(Math.hypot(h.x,h.z)<=BULL_ARENA.radius-.65+1e-6);});
test('horn contact ejects once along a curved flight, records survival and preserves bull momentum',()=>{const {m,b,h}=round();h.x=1;h.z=2.5;m.tick(.05,100);assert.equal(h.alive,false);assert(h.flight);assert(b.lift>0);assert(b.speed>7);const survived=h.survival;m.tick(.1,100);assert(h.y>0);for(let i=0;i<16;i++)m.tick(.1,100);assert.equal(h.y,0);assert(Math.hypot(h.x,h.z)>BULL_ARENA.radius);assert.equal(h.survival,survived);});
test('rear and side contact are safe; wall causes recoil, speed reset and temporary stun',()=>{const {m,b,h}=round();h.x=0;h.z=-1;m.tick(.01);assert(h.alive);h.x=10;h.z=0;b.z=BULL_ARENA.radius-2.1;b.speed=15;m.tick(.1);assert(b.stun>0);assert.equal(b.speed,7);const z=b.z;m.tick(.1);assert(b.z<z);assert(b.stun<.8);});
test('last victim finishes with bull victory but continues flying after the result',()=>{const {m,b,h}=round(2);h.x=0;h.z=2;m.tick(.05);assert.equal(m.phase,'finished');assert.equal(m.results.winner,'bull');m.tick(.1);assert(h.y>0);assert.equal(m.results.players.find(p=>p.id===h.id).survival,h.survival);});
test('timeout and disconnected bull award humans; reconnect never revives an eliminated runner',()=>{const {m,h,b}=round();m.bull.elapsed=m.duration-.05;h.x=15;h.z=0;m.tick(.1);assert.equal(m.results.winner,'humans');assert.equal(h.survival,m.duration);m.lobby();m.start();m.disconnect(b.id);m.tick(.05);assert.equal(m.results.winner,'humans');m.lobby();b.connected=true;m.start();h.x=0;h.z=2;m.tick(.05);m.disconnect(h.id);const token=h.token;m.join('new',token);assert.equal(h.alive,false);});
