server {
    listen 80;
    listen [::]:80;
    server_name dirt-rally.115.68.208.145.sslip.io;
    location ^~ /.well-known/acme-challenge/ {
        root /var/lib/letsencrypt;
        default_type text/plain;
        try_files $uri =404;
    }
    location / { return 503; }
}
